name: build-latest

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 6 * * *"

steps:
  - uses: actions/checkout@v2

  - name: Login to DockerHub
    uses: docker/login-action@v1
    with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Build and push
    if: github.ref == 'refs/heads/main'
    uses: docker/build-push-action@v2
    with:
      context: .
      push: true
      tags: storjstrategy/partridge:latest
